# Use uma imagem base do Node para construir o projeto
FROM node:14 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Use uma imagem base do Nginx para servir a aplicação
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
